//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BackOffice.WS.Tester.ArchivoSv {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BOArchivoSoap", Namespace="http://boarchivo.dgr.gov.ar/")]
    public partial class BOArchivo : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetArchivosOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetArchivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetArchivoNoUrlOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarArchivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmarArchivosOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetIdTempOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BOArchivo() {
            this.Url = global::BackOffice.WS.Tester.Properties.Settings.Default.BackOffice_WS_Tester_ArchivoSv_BOArchivo;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetArchivosCompletedEventHandler GetArchivosCompleted;
        
        /// <remarks/>
        public event GetArchivoCompletedEventHandler GetArchivoCompleted;
        
        /// <remarks/>
        public event GetArchivoNoUrlCompletedEventHandler GetArchivoNoUrlCompleted;
        
        /// <remarks/>
        public event AgregarArchivoCompletedEventHandler AgregarArchivoCompleted;
        
        /// <remarks/>
        public event ConfirmarArchivosCompletedEventHandler ConfirmarArchivosCompleted;
        
        /// <remarks/>
        public event GetIdTempCompletedEventHandler GetIdTempCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://boarchivo.dgr.gov.ar/GetArchivos", RequestNamespace="http://boarchivo.dgr.gov.ar/", ResponseNamespace="http://boarchivo.dgr.gov.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RespuestaGenericaOfEArchivo GetArchivos(QueryFilters filters) {
            object[] results = this.Invoke("GetArchivos", new object[] {
                        filters});
            return ((RespuestaGenericaOfEArchivo)(results[0]));
        }
        
        /// <remarks/>
        public void GetArchivosAsync(QueryFilters filters) {
            this.GetArchivosAsync(filters, null);
        }
        
        /// <remarks/>
        public void GetArchivosAsync(QueryFilters filters, object userState) {
            if ((this.GetArchivosOperationCompleted == null)) {
                this.GetArchivosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetArchivosOperationCompleted);
            }
            this.InvokeAsync("GetArchivos", new object[] {
                        filters}, this.GetArchivosOperationCompleted, userState);
        }
        
        private void OnGetArchivosOperationCompleted(object arg) {
            if ((this.GetArchivosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetArchivosCompleted(this, new GetArchivosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://boarchivo.dgr.gov.ar/GetArchivo", RequestNamespace="http://boarchivo.dgr.gov.ar/", ResponseNamespace="http://boarchivo.dgr.gov.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RespuestaGenericaOfEArchivo GetArchivo(System.Guid id) {
            object[] results = this.Invoke("GetArchivo", new object[] {
                        id});
            return ((RespuestaGenericaOfEArchivo)(results[0]));
        }
        
        /// <remarks/>
        public void GetArchivoAsync(System.Guid id) {
            this.GetArchivoAsync(id, null);
        }
        
        /// <remarks/>
        public void GetArchivoAsync(System.Guid id, object userState) {
            if ((this.GetArchivoOperationCompleted == null)) {
                this.GetArchivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetArchivoOperationCompleted);
            }
            this.InvokeAsync("GetArchivo", new object[] {
                        id}, this.GetArchivoOperationCompleted, userState);
        }
        
        private void OnGetArchivoOperationCompleted(object arg) {
            if ((this.GetArchivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetArchivoCompleted(this, new GetArchivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://boarchivo.dgr.gov.ar/GetArchivoNoUrl", RequestNamespace="http://boarchivo.dgr.gov.ar/", ResponseNamespace="http://boarchivo.dgr.gov.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RespuestaGenericaOfEArchivo GetArchivoNoUrl(System.Guid id, bool noUrl) {
            object[] results = this.Invoke("GetArchivoNoUrl", new object[] {
                        id,
                        noUrl});
            return ((RespuestaGenericaOfEArchivo)(results[0]));
        }
        
        /// <remarks/>
        public void GetArchivoNoUrlAsync(System.Guid id, bool noUrl) {
            this.GetArchivoNoUrlAsync(id, noUrl, null);
        }
        
        /// <remarks/>
        public void GetArchivoNoUrlAsync(System.Guid id, bool noUrl, object userState) {
            if ((this.GetArchivoNoUrlOperationCompleted == null)) {
                this.GetArchivoNoUrlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetArchivoNoUrlOperationCompleted);
            }
            this.InvokeAsync("GetArchivoNoUrl", new object[] {
                        id,
                        noUrl}, this.GetArchivoNoUrlOperationCompleted, userState);
        }
        
        private void OnGetArchivoNoUrlOperationCompleted(object arg) {
            if ((this.GetArchivoNoUrlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetArchivoNoUrlCompleted(this, new GetArchivoNoUrlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://boarchivo.dgr.gov.ar/AgregarArchivo", RequestNamespace="http://boarchivo.dgr.gov.ar/", ResponseNamespace="http://boarchivo.dgr.gov.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RespuestaGenericaOfBoolean AgregarArchivo(EArchivo entidad, bool esTemporal) {
            object[] results = this.Invoke("AgregarArchivo", new object[] {
                        entidad,
                        esTemporal});
            return ((RespuestaGenericaOfBoolean)(results[0]));
        }
        
        /// <remarks/>
        public void AgregarArchivoAsync(EArchivo entidad, bool esTemporal) {
            this.AgregarArchivoAsync(entidad, esTemporal, null);
        }
        
        /// <remarks/>
        public void AgregarArchivoAsync(EArchivo entidad, bool esTemporal, object userState) {
            if ((this.AgregarArchivoOperationCompleted == null)) {
                this.AgregarArchivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarArchivoOperationCompleted);
            }
            this.InvokeAsync("AgregarArchivo", new object[] {
                        entidad,
                        esTemporal}, this.AgregarArchivoOperationCompleted, userState);
        }
        
        private void OnAgregarArchivoOperationCompleted(object arg) {
            if ((this.AgregarArchivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarArchivoCompleted(this, new AgregarArchivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://boarchivo.dgr.gov.ar/ConfirmarArchivos", RequestNamespace="http://boarchivo.dgr.gov.ar/", ResponseNamespace="http://boarchivo.dgr.gov.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RespuestaGenericaOfBoolean ConfirmarArchivos(Confirmacion entidad) {
            object[] results = this.Invoke("ConfirmarArchivos", new object[] {
                        entidad});
            return ((RespuestaGenericaOfBoolean)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmarArchivosAsync(Confirmacion entidad) {
            this.ConfirmarArchivosAsync(entidad, null);
        }
        
        /// <remarks/>
        public void ConfirmarArchivosAsync(Confirmacion entidad, object userState) {
            if ((this.ConfirmarArchivosOperationCompleted == null)) {
                this.ConfirmarArchivosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmarArchivosOperationCompleted);
            }
            this.InvokeAsync("ConfirmarArchivos", new object[] {
                        entidad}, this.ConfirmarArchivosOperationCompleted, userState);
        }
        
        private void OnConfirmarArchivosOperationCompleted(object arg) {
            if ((this.ConfirmarArchivosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmarArchivosCompleted(this, new ConfirmarArchivosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://boarchivo.dgr.gov.ar/GetIdTemp", RequestNamespace="http://boarchivo.dgr.gov.ar/", ResponseNamespace="http://boarchivo.dgr.gov.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RespuestaGenericaOfString GetIdTemp(string codSistema) {
            object[] results = this.Invoke("GetIdTemp", new object[] {
                        codSistema});
            return ((RespuestaGenericaOfString)(results[0]));
        }
        
        /// <remarks/>
        public void GetIdTempAsync(string codSistema) {
            this.GetIdTempAsync(codSistema, null);
        }
        
        /// <remarks/>
        public void GetIdTempAsync(string codSistema, object userState) {
            if ((this.GetIdTempOperationCompleted == null)) {
                this.GetIdTempOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetIdTempOperationCompleted);
            }
            this.InvokeAsync("GetIdTemp", new object[] {
                        codSistema}, this.GetIdTempOperationCompleted, userState);
        }
        
        private void OnGetIdTempOperationCompleted(object arg) {
            if ((this.GetIdTempCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetIdTempCompleted(this, new GetIdTempCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://boarchivo.dgr.gov.ar/")]
    public partial class QueryFilters {
        
        private object idField;
        
        private int idRefField;
        
        private System.Guid idGField;
        
        private System.Nullable<System.DateTime> dateField;
        
        private string fileNameField;
        
        private string cUITField;
        
        private string searchField;
        
        private int pageSizeField;
        
        private int pageNumberField;
        
        private string sortField;
        
        private string sortDirField;
        
        /// <remarks/>
        public object Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int IdRef {
            get {
                return this.idRefField;
            }
            set {
                this.idRefField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid IdG {
            get {
                return this.idGField;
            }
            set {
                this.idGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        public string CUIT {
            get {
                return this.cUITField;
            }
            set {
                this.cUITField = value;
            }
        }
        
        /// <remarks/>
        public string Search {
            get {
                return this.searchField;
            }
            set {
                this.searchField = value;
            }
        }
        
        /// <remarks/>
        public int PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
        
        /// <remarks/>
        public int PageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                this.pageNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Sort {
            get {
                return this.sortField;
            }
            set {
                this.sortField = value;
            }
        }
        
        /// <remarks/>
        public string SortDir {
            get {
                return this.sortDirField;
            }
            set {
                this.sortDirField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://boarchivo.dgr.gov.ar/")]
    public partial class RespuestaGenericaOfString {
        
        private bool okField;
        
        private int errorCodeField;
        
        private string mensajeField;
        
        private string mensajeOriginalField;
        
        private int nroEntidadesObtenidasOModificadasField;
        
        private string[] listaItemsField;
        
        private string dataItemField;
        
        private int totalRegsField;
        
        private int cantidadRegField;
        
        private int paginaField;
        
        /// <remarks/>
        public bool Ok {
            get {
                return this.okField;
            }
            set {
                this.okField = value;
            }
        }
        
        /// <remarks/>
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public string MensajeOriginal {
            get {
                return this.mensajeOriginalField;
            }
            set {
                this.mensajeOriginalField = value;
            }
        }
        
        /// <remarks/>
        public int NroEntidadesObtenidasOModificadas {
            get {
                return this.nroEntidadesObtenidasOModificadasField;
            }
            set {
                this.nroEntidadesObtenidasOModificadasField = value;
            }
        }
        
        /// <remarks/>
        public string[] ListaItems {
            get {
                return this.listaItemsField;
            }
            set {
                this.listaItemsField = value;
            }
        }
        
        /// <remarks/>
        public string DataItem {
            get {
                return this.dataItemField;
            }
            set {
                this.dataItemField = value;
            }
        }
        
        /// <remarks/>
        public int TotalRegs {
            get {
                return this.totalRegsField;
            }
            set {
                this.totalRegsField = value;
            }
        }
        
        /// <remarks/>
        public int CantidadReg {
            get {
                return this.cantidadRegField;
            }
            set {
                this.cantidadRegField = value;
            }
        }
        
        /// <remarks/>
        public int Pagina {
            get {
                return this.paginaField;
            }
            set {
                this.paginaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://boarchivo.dgr.gov.ar/")]
    public partial class Confirmacion {
        
        private string claveTemporalField;
        
        private string solicitudIdField;
        
        /// <remarks/>
        public string ClaveTemporal {
            get {
                return this.claveTemporalField;
            }
            set {
                this.claveTemporalField = value;
            }
        }
        
        /// <remarks/>
        public string SolicitudId {
            get {
                return this.solicitudIdField;
            }
            set {
                this.solicitudIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://boarchivo.dgr.gov.ar/")]
    public partial class RespuestaGenericaOfBoolean {
        
        private bool okField;
        
        private int errorCodeField;
        
        private string mensajeField;
        
        private string mensajeOriginalField;
        
        private int nroEntidadesObtenidasOModificadasField;
        
        private bool[] listaItemsField;
        
        private bool dataItemField;
        
        private int totalRegsField;
        
        private int cantidadRegField;
        
        private int paginaField;
        
        /// <remarks/>
        public bool Ok {
            get {
                return this.okField;
            }
            set {
                this.okField = value;
            }
        }
        
        /// <remarks/>
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public string MensajeOriginal {
            get {
                return this.mensajeOriginalField;
            }
            set {
                this.mensajeOriginalField = value;
            }
        }
        
        /// <remarks/>
        public int NroEntidadesObtenidasOModificadas {
            get {
                return this.nroEntidadesObtenidasOModificadasField;
            }
            set {
                this.nroEntidadesObtenidasOModificadasField = value;
            }
        }
        
        /// <remarks/>
        public bool[] ListaItems {
            get {
                return this.listaItemsField;
            }
            set {
                this.listaItemsField = value;
            }
        }
        
        /// <remarks/>
        public bool DataItem {
            get {
                return this.dataItemField;
            }
            set {
                this.dataItemField = value;
            }
        }
        
        /// <remarks/>
        public int TotalRegs {
            get {
                return this.totalRegsField;
            }
            set {
                this.totalRegsField = value;
            }
        }
        
        /// <remarks/>
        public int CantidadReg {
            get {
                return this.cantidadRegField;
            }
            set {
                this.cantidadRegField = value;
            }
        }
        
        /// <remarks/>
        public int Pagina {
            get {
                return this.paginaField;
            }
            set {
                this.paginaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://boarchivo.dgr.gov.ar/")]
    public partial class EArchivo {
        
        private System.Guid idField;
        
        private string codigoSistemaField;
        
        private int estadoEArchivoIdField;
        
        private int requerimientoIdField;
        
        private string solicitudIdField;
        
        private string tipoSolicitudField;
        
        private string cUITField;
        
        private string nombreArchivoField;
        
        private string descripcionField;
        
        private string rutaField;
        
        private System.DateTime fechaIndexacionField;
        
        private string hashField;
        
        private object archivoField;
        
        private string claveTemporalField;
        
        /// <remarks/>
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoSistema {
            get {
                return this.codigoSistemaField;
            }
            set {
                this.codigoSistemaField = value;
            }
        }
        
        /// <remarks/>
        public int EstadoEArchivoId {
            get {
                return this.estadoEArchivoIdField;
            }
            set {
                this.estadoEArchivoIdField = value;
            }
        }
        
        /// <remarks/>
        public int RequerimientoId {
            get {
                return this.requerimientoIdField;
            }
            set {
                this.requerimientoIdField = value;
            }
        }
        
        /// <remarks/>
        public string SolicitudId {
            get {
                return this.solicitudIdField;
            }
            set {
                this.solicitudIdField = value;
            }
        }
        
        /// <remarks/>
        public string TipoSolicitud {
            get {
                return this.tipoSolicitudField;
            }
            set {
                this.tipoSolicitudField = value;
            }
        }
        
        /// <remarks/>
        public string CUIT {
            get {
                return this.cUITField;
            }
            set {
                this.cUITField = value;
            }
        }
        
        /// <remarks/>
        public string NombreArchivo {
            get {
                return this.nombreArchivoField;
            }
            set {
                this.nombreArchivoField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string Ruta {
            get {
                return this.rutaField;
            }
            set {
                this.rutaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaIndexacion {
            get {
                return this.fechaIndexacionField;
            }
            set {
                this.fechaIndexacionField = value;
            }
        }
        
        /// <remarks/>
        public string Hash {
            get {
                return this.hashField;
            }
            set {
                this.hashField = value;
            }
        }
        
        /// <remarks/>
        public object Archivo {
            get {
                return this.archivoField;
            }
            set {
                this.archivoField = value;
            }
        }
        
        /// <remarks/>
        public string ClaveTemporal {
            get {
                return this.claveTemporalField;
            }
            set {
                this.claveTemporalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://boarchivo.dgr.gov.ar/")]
    public partial class RespuestaGenericaOfEArchivo {
        
        private bool okField;
        
        private int errorCodeField;
        
        private string mensajeField;
        
        private string mensajeOriginalField;
        
        private int nroEntidadesObtenidasOModificadasField;
        
        private EArchivo[] listaItemsField;
        
        private EArchivo dataItemField;
        
        private int totalRegsField;
        
        private int cantidadRegField;
        
        private int paginaField;
        
        /// <remarks/>
        public bool Ok {
            get {
                return this.okField;
            }
            set {
                this.okField = value;
            }
        }
        
        /// <remarks/>
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public string MensajeOriginal {
            get {
                return this.mensajeOriginalField;
            }
            set {
                this.mensajeOriginalField = value;
            }
        }
        
        /// <remarks/>
        public int NroEntidadesObtenidasOModificadas {
            get {
                return this.nroEntidadesObtenidasOModificadasField;
            }
            set {
                this.nroEntidadesObtenidasOModificadasField = value;
            }
        }
        
        /// <remarks/>
        public EArchivo[] ListaItems {
            get {
                return this.listaItemsField;
            }
            set {
                this.listaItemsField = value;
            }
        }
        
        /// <remarks/>
        public EArchivo DataItem {
            get {
                return this.dataItemField;
            }
            set {
                this.dataItemField = value;
            }
        }
        
        /// <remarks/>
        public int TotalRegs {
            get {
                return this.totalRegsField;
            }
            set {
                this.totalRegsField = value;
            }
        }
        
        /// <remarks/>
        public int CantidadReg {
            get {
                return this.cantidadRegField;
            }
            set {
                this.cantidadRegField = value;
            }
        }
        
        /// <remarks/>
        public int Pagina {
            get {
                return this.paginaField;
            }
            set {
                this.paginaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetArchivosCompletedEventHandler(object sender, GetArchivosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetArchivosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetArchivosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaGenericaOfEArchivo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaGenericaOfEArchivo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetArchivoCompletedEventHandler(object sender, GetArchivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetArchivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetArchivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaGenericaOfEArchivo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaGenericaOfEArchivo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetArchivoNoUrlCompletedEventHandler(object sender, GetArchivoNoUrlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetArchivoNoUrlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetArchivoNoUrlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaGenericaOfEArchivo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaGenericaOfEArchivo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AgregarArchivoCompletedEventHandler(object sender, AgregarArchivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarArchivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgregarArchivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaGenericaOfBoolean Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaGenericaOfBoolean)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConfirmarArchivosCompletedEventHandler(object sender, ConfirmarArchivosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmarArchivosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmarArchivosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaGenericaOfBoolean Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaGenericaOfBoolean)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetIdTempCompletedEventHandler(object sender, GetIdTempCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetIdTempCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetIdTempCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaGenericaOfString Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaGenericaOfString)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591